version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot-server:latest
    container_name: bot-server
    ports:
      - "12345:12345"
    depends_on:
      - redis
      - postgres
      - mongodb
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgres://admin:admin@postgres:5432/telegram_db?sslmode=disable
      - MONGODB_URL=mongodb://mongodb:27017
    networks:
      - bot-network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - bot-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: telegram_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - bot-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - bot-network

networks:
  bot-network:
    name: bot-network
volumes:
  postgres_data:
  mongodb_data: